import { db } from "@/lib/prisma";
import { notFound } from "next/navigation";

interface Props {
  params: Promise<{ token: string }>;
}

export default async function SharePage({ params }: Props) {
  const { token } = await params;
  const shareLog = await db.shareLog.findUnique({
    where: { shareToken: token },
    include: {
      session: {
        include: {
          tryOnJobs: {
            where: { status: "COMPLETED" },
            include: { results: { orderBy: { poseIndex: "asc" } } },
            orderBy: { completedAt: "desc" },
            take: 1,
          },
          store: { select: { name: true, brandColor: true } },
        },
      },
    },
  });

  if (!shareLog) notFound();

  if (shareLog.expiresAt < new Date()) {
    return (
      <div className="min-h-screen bg-[#0A0A0A] flex flex-col items-center justify-center text-center p-8">
        <div className="text-5xl mb-4">⏰</div>
        <h1 className="text-white text-2xl font-light mb-2">Link Expired</h1>
        <p className="text-white/40">Share links are valid for 24 hours.</p>
      </div>
    );
  }

  await db.shareLog.update({
    where: { id: shareLog.id },
    data: { openCount: { increment: 1 }, openedAt: shareLog.openedAt ?? new Date() },
  });

  const results = shareLog.session.tryOnJobs[0]?.results ?? [];
  const storeName = shareLog.session.store.name;
  const customerName = shareLog.session.customerName;

  return (
    <div className="min-h-screen bg-[#0A0A0A] flex flex-col">
      {/* Header */}
      <div className="px-6 py-5 border-b border-white/10 text-center">
        <p className="text-white/40 text-sm">{storeName}</p>
        <h1 className="text-white text-xl font-light mt-1">
          {customerName}&apos;s Virtual Try-On Looks
        </h1>
      </div>

      {/* Gallery */}
      <div className="flex-1 p-4">
        {results.length > 0 ? (
          <div className="grid grid-cols-2 gap-3 max-w-lg mx-auto">
            {results.map((result) => (
              <div key={result.id} className="aspect-[3/4] rounded-xl overflow-hidden bg-[#141414]">
                <img
                  src={result.imageUrl}
                  alt={`Pose ${result.poseIndex}`}
                  className="w-full h-full object-cover"
                />
              </div>
            ))}
          </div>
        ) : (
          <div className="flex items-center justify-center h-64">
            <div className="text-center">
              <div className="text-5xl mb-4">🎨</div>
              <p className="text-white/40">No generated images in this session.</p>
            </div>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="px-6 py-6 text-center border-t border-white/10">
        <p className="text-white/30 text-xs">
          Generated by VirtualFit AI Try-On Platform · {storeName}
        </p>
      </div>
    </div>
  );
}
